// Code generated by go run internal/chunker/generate/main.go; DO NOT EDIT.

package chunker

import (
	"fmt"
	"path/filepath"
	"strings"

	sitter "github.com/smacker/go-tree-sitter"
	csharp "github.com/smacker/go-tree-sitter/csharp"
	elixir "github.com/smacker/go-tree-sitter/elixir"
	golang "github.com/smacker/go-tree-sitter/golang"
	java "github.com/smacker/go-tree-sitter/java"
	javascript "github.com/smacker/go-tree-sitter/javascript"
	kotlin "github.com/smacker/go-tree-sitter/kotlin"
	php "github.com/smacker/go-tree-sitter/php"
	python "github.com/smacker/go-tree-sitter/python"
	rust "github.com/smacker/go-tree-sitter/rust"
	swift "github.com/smacker/go-tree-sitter/swift"
	tsx "github.com/smacker/go-tree-sitter/typescript/tsx"
	typescript "github.com/smacker/go-tree-sitter/typescript/typescript"
)

// grammarRegistry maps grammar names (from config) to tree-sitter language getters.
var grammarRegistry = map[string]func() *sitter.Language{
	"c_sharp":    csharp.GetLanguage,
	"elixir":     elixir.GetLanguage,
	"go":         golang.GetLanguage,
	"java":       java.GetLanguage,
	"javascript": javascript.GetLanguage,
	"jsx":        javascript.GetLanguage,
	"kotlin":     kotlin.GetLanguage,
	"php":        php.GetLanguage,
	"python":     python.GetLanguage,
	"rust":       rust.GetLanguage,
	"swift":      swift.GetLanguage,
	"tsx":        tsx.GetLanguage,
	"typescript": typescript.GetLanguage,
}

// languageToGrammar maps user-friendly language names to grammar names.
var languageToGrammar = map[string]string{
	"csharp":     "c_sharp",
	"elixir":     "elixir",
	"go":         "go",
	"java":       "java",
	"javascript": "javascript",
	"jsx":        "jsx",
	"kotlin":     "kotlin",
	"php":        "php",
	"python":     "python",
	"rust":       "rust",
	"swift":      "swift",
	"tsx":        "tsx",
	"typescript": "typescript",
}

// extensionToLanguage maps file extensions to user-friendly language names.
var extensionToLanguage = map[string]string{
	".cjs":   "javascript",
	".cs":    "csharp",
	".cts":   "typescript",
	".ex":    "elixir",
	".exs":   "elixir",
	".go":    "go",
	".java":  "java",
	".js":    "javascript",
	".jsx":   "jsx",
	".kt":    "kotlin",
	".kts":   "kotlin",
	".mjs":   "javascript",
	".mts":   "typescript",
	".php":   "php",
	".php3":  "php",
	".php4":  "php",
	".php5":  "php",
	".phps":  "php",
	".phtml": "php",
	".py":    "python",
	".pyi":   "python",
	".pyw":   "python",
	".rs":    "rust",
	".swift": "swift",
	".ts":    "typescript",
	".tsx":   "tsx",
}

// supportedLanguages is the list of all supported language names.
var supportedLanguages = []string{
	"csharp",
	"elixir",
	"go",
	"java",
	"javascript",
	"jsx",
	"kotlin",
	"php",
	"python",
	"rust",
	"swift",
	"tsx",
	"typescript",
}

// DetectLanguageByExtension returns the language name for a given filename.
// Returns "unknown" if the extension is not recognized.
func DetectLanguageByExtension(filename string) string {
	ext := filepath.Ext(filename)
	// Enforce case-sensitivity: only lowercase extensions match
	if ext != strings.ToLower(ext) {
		return "unknown"
	}
	if lang, ok := extensionToLanguage[ext]; ok {
		return lang
	}
	return "unknown"
}

// GetGrammarForLanguage returns the grammar name for the given language name.
// Returns the language name itself if not found (for backwards compatibility).
func GetGrammarForLanguage(lang string) string {
	if grammar, ok := languageToGrammar[lang]; ok {
		return grammar
	}
	return lang
}

// GetLanguageGrammar returns the tree-sitter language for the given grammar name.
func GetLanguageGrammar(name string) (*sitter.Language, error) {
	getter, ok := grammarRegistry[name]
	if !ok {
		return nil, fmt.Errorf("unsupported grammar: %s", name)
	}
	return getter(), nil
}

// IsLanguageSupported returns true if the given language name is supported.
func IsLanguageSupported(lang string) bool {
	_, ok := languageToGrammar[lang]
	return ok
}

// IsGrammarSupported returns true if the given grammar name is supported.
func IsGrammarSupported(name string) bool {
	_, ok := grammarRegistry[name]
	return ok
}

// SupportedLanguages returns a list of all supported language names.
func SupportedLanguages() []string {
	return supportedLanguages
}
